/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/chinaGirl.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ChinaGirlModel({selectedImote}:any,props:any) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../Models/chinaGirl.glb')
  const { actions,names } = useAnimations(animations, group)
  console.log(names,'china girl men names');
  const currentAction = useRef<any>(null);
  console.log(names,'china girl men names');
  useEffect(() => {
   
    const findIndex: number = names.findIndex((item: any) => item === selectedImote);
    if (findIndex !== -1) {
      if (currentAction.current) {
        currentAction.current.stop(); // Stop the currently playing animation
      }
      currentAction.current = actions[names[findIndex]]; // Update the current action
      currentAction.current.reset().fadeIn(0.5).play(); // Play the new animation
    }
  }, [selectedImote]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature002" rotation={[Math.PI / 2, 0, 5.5]} position={[0,-1.3,0]} scale={0.013}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Kachujin">
            <skinnedMesh name="Kachujin_1" geometry={nodes.Kachujin_1.geometry} material={materials.kachujin_MAT} skeleton={nodes.Kachujin_1.skeleton} />
            <skinnedMesh name="Kachujin_2" geometry={nodes.Kachujin_2.geometry} material={materials.kachujin_MAT_} skeleton={nodes.Kachujin_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

export default ChinaGirlModel
useGLTF.preload('../../../Models/chinaGirl.glb')
