/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/cyberCity.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three';
export function CyberCity({onModelLoaded}:any,props:any) {
  const { nodes, materials } = useGLTF('../../../Models/cyberCity.glb')
  if (nodes && materials) {
    onModelLoaded();
  }
  const textureLoader = new TextureLoader();
  const texture1 = textureLoader.load('../../../texture/internal_ground_ao_texture.jpeg');


 

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.building_j1.geometry} material={nodes.building_j1.material} position={[27.413, 3.182, -16.72]} rotation={[Math.PI, -0.408, Math.PI]} scale={[2.176, 3.8, 3.8]} />
      <mesh geometry={nodes.bui_j2.geometry} material={nodes.bui_j2.material} position={[-4.861, 3.073, 33.263]} rotation={[-Math.PI, 0.79, -Math.PI]} scale={[2.176, 3.8, 3.8]} />
      <mesh geometry={nodes.j21.geometry} material={nodes.j21.material} position={[-0.122, 3.172, 28.829]} rotation={[-Math.PI, 0.79, -Math.PI]} scale={[2.176, 3.8, 3.8]} />
      <mesh geometry={nodes.Ground001.geometry} material={nodes.Ground001.material} position={[2.042, -1.337, 1.405]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[45.335, 1.011, 3.872]} scale={[14.511, 26.465, 59.452]} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[12.634, -1.825, -46.508]} />
      <mesh geometry={nodes.Ground002.geometry} material={nodes.Ground002.material} position={[-5.529, -0.829, -36.049]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-118.403, 5.536, 12.622]} scale={[89.448, 2.059, 51.215]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[1.249, 0.974, 52.205]} rotation={[-3.139, -1.566, -3.139]} scale={[11.21, 26.465, 56.733]} />
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-122.043, 10.968, -36.084]} scale={[131.342, 14.986, 14.986]} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-120.375, 4.409, -37.868]} />
      <mesh geometry={nodes.Ground008.geometry} material={nodes.Ground008.material} position={[15.135, -1.028, -6.667]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.Ground003.geometry} material={nodes.Ground003.material} position={[-26.449, -0.576, -36.09]} />
      <mesh geometry={nodes.Ground004.geometry} material={nodes.Ground004.material} position={[-26.541, -0.659, -15.147]} />
      <mesh geometry={nodes.Ground005.geometry} material={nodes.Ground005.material} position={[-26.449, -1.028, 35.463]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.Ground006.geometry} material={nodes.Ground006.material} position={[-5.375, -0.835, 35.463]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.Ground007.geometry} material={nodes.Ground007.material} position={[-5.48, -1.674, 20.307]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} position={[-51.604, 12.217, -37.723]} scale={[131.342, 14.986, 14.986]} />
      <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[12.634, -1.825, -46.508]} />
      <mesh geometry={nodes.building_138002.geometry} material={nodes.building_138002.material} position={[-11.085, -0.824, -21.342]} scale={[-1.577, -1.577, -2.164]} />
      <mesh geometry={nodes.building_138003.geometry} material={nodes.building_138003.material} position={[1.915, -1.014, -23.342]} scale={[-1.577, -1.577, -2.164]} />
      <mesh geometry={nodes.building_138005.geometry} material={nodes.building_138005.material} position={[3.365, -1.014, -12.062]} scale={[-1.577, -1.577, -3.351]} />
      <mesh geometry={nodes.building_154.geometry} material={nodes.building_154.material} position={[-13.325, -0.931, -9.542]} rotation={[0, -0.318, 0]} scale={[1.482, 1.157, 2.654]} />
      <mesh geometry={nodes.building_138006.geometry} material={nodes.building_138006.material} position={[3.22, -0.824, 3.759]} scale={[-1.577, -1.577, -2.164]} />
      <mesh geometry={nodes.Circle005.geometry} material={nodes.Circle005.material} position={[-11.401, 2.578, 21.701]} scale={[5.939, 10.474, 5.939]} />
      <mesh geometry={nodes['DOOR`S_LOCK009'].geometry} material={nodes['DOOR`S_LOCK009'].material} position={[-13.457, -0.488, 0.035]} rotation={[Math.PI, -0.005, Math.PI]} scale={[0.007, 0.018, 0.065]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[3.591, 0.702, -9.116]} scale={[1, 1, 3.156]} />
      <mesh geometry={nodes.building_138001.geometry} material={nodes.building_138001.material} position={[-13.085, -1.243, 3.658]} scale={[-1.549, -1.549, -2.595]} />
      <mesh geometry={nodes.building_138004.geometry} material={nodes.building_138004.material} position={[-3.085, -0.977, -23.342]} scale={[-0.728, -0.728, -0.998]} />
      <mesh geometry={nodes.ROADS001.geometry} material={nodes.ROADS001.material} position={[0.967, -0.947, 18.809]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.ROAD2001.geometry} material={nodes.ROAD2001.material} position={[-8.254, -0.947, -26.12]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.ROAD_2002.geometry} material={nodes.ROAD_2002.material} position={[23.3, -0.947, -23.345]} scale={[30.433, 30.433, 39.947]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-118.403, 1.948, 12.622]} scale={[89.448, 2.059, 2.059]} />
      <mesh geometry={nodes.building_137002.geometry} material={nodes.building_137002.material} position={[-4.251, 7.904, 17.575]} />
      <mesh geometry={nodes.building_137004.geometry} material={nodes.building_137004.material} position={[26.607, 7.904, 31.79]} />
      <mesh geometry={nodes.building_137005.geometry} material={nodes.building_137005.material} position={[24.487, 7.904, 9.832]} rotation={[0, 1.245, 0]} />
      <mesh geometry={nodes.building_137009.geometry} material={nodes.building_137009.material} position={[24.487, 7.904, 3.475]} rotation={[0, 1.245, 0]} />
      <mesh geometry={nodes.building_137010.geometry} material={nodes.building_137010.material} position={[24.487, 5.996, -2.65]} rotation={[0, 1.245, 0]} scale={[0.913, 0.818, 0.913]} />
      <mesh geometry={nodes.building_137.geometry} material={nodes.building_137.material} position={[-13.328, 4.248, 7.482]} scale={[0.497, 0.902, 0.435]} />
      <mesh geometry={nodes.building_137001.geometry} material={nodes.building_137001.material} position={[4.07, 4.248, 17.743]} rotation={[-Math.PI, 0.973, -Math.PI]} scale={[0.497, 0.902, 0.435]} />
      <mesh geometry={nodes.building_137008.geometry} material={nodes.building_137008.material} position={[14.248, 3.778, -1.199]} rotation={[Math.PI, -1.127, Math.PI]} scale={[0.497, 0.902, 0.435]} />
      <mesh geometry={nodes.building_137006.geometry} material={nodes.building_137006.material} position={[14.248, 2.985, 2.948]} rotation={[Math.PI, -1.127, Math.PI]} scale={[0.497, 0.721, 0.435]} />
      <mesh geometry={nodes.building_137007.geometry} material={nodes.building_137007.material} position={[14.248, 3.969, 6.76]} rotation={[Math.PI, -1.127, Math.PI]} scale={[0.713, 0.902, 0.484]} />
      <mesh geometry={nodes.building_137012.geometry} material={nodes.building_137012.material} position={[-9.659, 4.248, 6.693]} rotation={[-Math.PI, 0.801, -Math.PI]} scale={[0.497, 0.902, 0.435]} />
      <mesh geometry={nodes.building_137011.geometry} material={nodes.building_137011.material} position={[-13.328, 4.248, 7.482]} scale={[0.497, 0.902, 0.435]} />
      <mesh geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[-7.553, 5.562, -10.706]} rotation={[0, -1.416, 0]} />
      <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-2.745, 5.616, -9.122]} rotation={[-Math.PI, 1.4, -Math.PI]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[3.591, 0.702, -9.116]} scale={[1, 1, 3.156]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[4.076, 2.033, -14.121]} scale={[1, 2.428, 1.405]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[4.591, -0.095, -9.116]} scale={[1, 1, 3.156]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[17.004, 0.479, -21.38]} scale={[1, 1, 3.156]} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[12.736, 1.907, -19.083]} rotation={[Math.PI, -0.001, Math.PI]} scale={[1, 1, 3.156]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[4.076, 2.033, -14.121]} scale={[1, 2.428, 1.405]} />
      <mesh geometry={nodes.building_153.geometry} material={nodes.building_153.material} position={[-12.739, 0.877, -9.367]} rotation={[-Math.PI, 0.324, -Math.PI]} scale={[1, 1, 2.16]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[18.052, -0.095, -18.993]} scale={[1, 1, 3.156]} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[12.51, -0.095, -18.991]} rotation={[Math.PI, -0.001, Math.PI]} />
      <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[2.892, 0.785, -17.388]} rotation={[3.141, -1.556, 3.141]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.building_153001.geometry} material={nodes.building_153001.material} position={[-12.739, 0.877, -9.367]} rotation={[-Math.PI, 0.324, -Math.PI]} scale={[1, 1, 2.16]} />
      <mesh geometry={nodes.building_153002.geometry} material={nodes.building_153002.material} position={[-12.739, 0.877, -9.367]} rotation={[-Math.PI, 0.324, -Math.PI]} scale={[1, 1, 2.16]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[2.892, 0.785, -17.388]} rotation={[Math.PI, -1.556, Math.PI]} />
      <mesh geometry={nodes.Cube027.geometry} material={nodes.Cube027.material} position={[2.892, 0.785, -17.388]} rotation={[3.141, -1.556, 3.141]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} position={[2.892, 0.785, -17.388]} rotation={[3.141, -1.556, 3.141]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[2.892, 0.785, -17.388]} rotation={[3.141, -1.556, 3.141]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[0.263, 0.785, -25.6]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[0.263, 0.785, -25.6]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[0.263, 0.785, -25.6]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[0.263, 0.785, -25.6]} scale={[1, 1, 2.055]} />
      <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[17.54, 0.397, 20.341]} scale={4.781} />
      <mesh geometry={nodes.Circle004.geometry} material={nodes.Circle004.material} position={[-11.401, 2.578, 21.701]} scale={[5.939, 10.474, 5.939]} />
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[-11.401, 2.578, 21.701]} scale={[5.939, 10.474, 5.939]} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[17.54, 0.397, 20.341]} scale={4.781} />
      <mesh geometry={nodes.Circle003.geometry} material={nodes.Circle003.material} position={[17.54, 0.397, 20.341]} />
      <mesh geometry={nodes.Circle006.geometry} material={nodes.Circle006.material} position={[-11.401, 2.578, 21.701]} scale={[5.939, 10.474, 5.939]} />
      <mesh geometry={nodes.building_144.geometry} material={nodes.building_144.material} position={[-11.638, -0.934, 21.662]} scale={6.425} />
      <mesh geometry={nodes.building_144001.geometry} material={nodes.building_144001.material} position={[17.675, -0.979, 20.458]} scale={5.225} />
      <mesh geometry={nodes.DOOR006.geometry} material={nodes.DOOR006.material} position={[4.071, -0.519, -25.405]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR007.geometry} material={nodes.DOOR007.material} position={[4.071, -0.519, -21.261]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR008.geometry} material={nodes.DOOR008.material} position={[-3.429, -0.519, -23.945]} rotation={[-Math.PI, 0.978, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR009.geometry} material={nodes.DOOR009.material} position={[-9.5, -0.519, -20.389]} rotation={[-Math.PI, 1.545, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR010.geometry} material={nodes.DOOR010.material} position={[-12.748, -0.519, -21.952]} rotation={[-Math.PI, 1.545, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR011.geometry} material={nodes.DOOR011.material} position={[-12.748, -0.519, -25.18]} rotation={[-Math.PI, 1.545, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.SIDE_WINDOW_2007.geometry} material={materials['Material.001']} position={[-3.588, -0.236, -22.539]} rotation={[-Math.PI, 1.233, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.SIDE_WINDOW_1007.geometry} material={materials['Material.001']} position={[-2.847, -0.236, -22.215]} rotation={[-Math.PI, 1.362, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes['DOOR`S_LOCK007'].geometry} material={nodes['DOOR`S_LOCK007'].material} position={[-2.532, -0.488, -23.379]} rotation={[0, 1.556, 0]} scale={[0.007, 0.018, 0.065]} />
      <mesh geometry={nodes['DOOR`S_LOCK005'].geometry} material={nodes['DOOR`S_LOCK005'].material} position={[4.127, -0.488, -0.837]} scale={[0.007, 0.018, 0.065]} />
      <mesh geometry={nodes.DOOR001.geometry} material={nodes.DOOR001.material} position={[4.805, -0.519, 4.712]} rotation={[-Math.PI, 1.545, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR002.geometry} material={nodes.DOOR002.material} position={[1.557, -0.519, 4.776]} rotation={[-Math.PI, 1.545, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR003.geometry} material={nodes.DOOR003.material} position={[1.557, -0.519, 1.19]} rotation={[-Math.PI, 1.545, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.DOOR004.geometry} material={nodes.DOOR004.material} position={[4.616, -0.519, 1.19]} rotation={[-Math.PI, 1.545, -Math.PI]} scale={[0.675, 0.673, 0.873]} />
      <mesh geometry={nodes.building_178006.geometry} material={nodes.building_178006.material} position={[-39.428, 11.894, -41.04]} rotation={[0, 1.2, 0]} />
      <mesh geometry={nodes.building_178001.geometry} material={nodes.building_178001.material} position={[-37.964, 11.894, -32.449]} rotation={[0, 1.2, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[26.845, 1.756, -36.452]} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[24.533, -0.128, -35.535]} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[21.281, -0.128, -35.535]} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[17.709, -0.128, -35.535]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[14.413, -0.128, -35.535]} />
      <mesh geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[-25.43, -0.128, 7.651]} rotation={[0, 1.254, 0]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-25.098, -0.128, 16.488]} rotation={[-Math.PI, 1.286, -Math.PI]} />
      <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[-25.098, -0.128, 24.197]} rotation={[-Math.PI, 1.286, -Math.PI]} />
      <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[-25.098, -0.128, 20.23]} rotation={[-Math.PI, 1.286, -Math.PI]} />
      <mesh geometry={nodes.building_137003.geometry} material={nodes.building_137003.material} position={[-3.247, 14.238, 17.421]} />
    </group>
  )
}

export default CyberCity
useGLTF.preload('../../../Models/cyberCity.glb')
