/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/footballBoy.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function FootBallBoyModel({selectedImote}:any,props:any) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../Models/footballBoy.glb')
  const { actions,names } = useAnimations(animations, group)
  console.log(names,'china girl men names');
  const currentAction = useRef<any>(null);
  console.log(names,'china girl men names');
  useEffect(() => {
   
    const findIndex: number = names.findIndex((item: any) => item === selectedImote);
    if (findIndex !== -1) {
      if (currentAction.current) {
        currentAction.current.stop(); // Stop the currently playing animation
      }
      currentAction.current = actions[names[findIndex]]; // Update the current action
      currentAction.current.reset().fadeIn(0.5).play(); // Play the new animation
    }
  }, [selectedImote]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature002" rotation={[Math.PI / 2, 0, 5.5]} position={[0,-1.3,0]} scale={0.013}>
          <primitive object={nodes.mixamorig5Hips} />
          <skinnedMesh name="Ch38_Body" geometry={nodes.Ch38_Body.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Body.skeleton} />
          <skinnedMesh name="Ch38_Eyelashes" geometry={nodes.Ch38_Eyelashes.geometry} material={materials.Ch38_hair} skeleton={nodes.Ch38_Eyelashes.skeleton} />
          <skinnedMesh name="Ch38_Hair" geometry={nodes.Ch38_Hair.geometry} material={materials.Ch38_hair} skeleton={nodes.Ch38_Hair.skeleton} />
          <skinnedMesh name="Ch38_Shirt" geometry={nodes.Ch38_Shirt.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Shirt.skeleton} />
          <skinnedMesh name="Ch38_Shoes" geometry={nodes.Ch38_Shoes.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Shoes.skeleton} />
          <skinnedMesh name="Ch38_Shorts" geometry={nodes.Ch38_Shorts.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Shorts.skeleton} />
          <skinnedMesh name="Ch38_Socks" geometry={nodes.Ch38_Socks.geometry} material={materials.Ch38_body} skeleton={nodes.Ch38_Socks.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default FootBallBoyModel

useGLTF.preload('../../../Models/footballBoy.glb')
