/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/plaza.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three';
export function Plaza(props:any) {

  const { nodes, materials } = useGLTF('../../../Models/plaza.glb')
  const textureLoader = new TextureLoader();

  const texture1 = textureLoader.load('../../../texture/plaque_Glow.jpg');
  const texture2 = textureLoader.load('../../../texture/plaza_Glow.jpg');
  const texture3 = textureLoader.load('../../../texture/plaza_RGBA.png');
  materials.opaque.map = texture2;
  materials.opaque.map = texture1;
  materials.opaque.map = texture3;
  materials.transparent.map = texture1;
  materials.transparent.map = texture2; 
  materials.transparent.map = texture3;
  materials.plaque.map = texture1;
  materials.plaque.map = texture2;
  materials.plaque.map = texture3;


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.opaque.geometry} material={materials.opaque} scale={0.01} />
      <mesh geometry={nodes.transparent.geometry} material={materials.transparent} scale={0.01} />
      <mesh geometry={nodes.plaque.geometry} material={materials.plaque} position={[-0.375, 0.099, -0.615]} scale={0.01} />
    </group>
  )
}

export default Plaza
useGLTF.preload('../../../Models/plaza.glb')
