// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.16 public/Models/redracer.glb -t 
// */

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Vector3 } from 'three'
type GLTFResult = GLTF & {
  nodes: {
    Ch20: THREE.SkinnedMesh
    mixamorig6Hips: THREE.Bone
  }
  materials: {
    Ch20_body: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>
function RedRacerModel({position}:any,props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./Models/redracer.glb') as GLTFResult
  console.log(position,'--');

  return (
    <group {...props} position={new THREE.Vector3(position.x,position.y,position.z)} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorig6Hips} />
        <skinnedMesh geometry={nodes.Ch20.geometry} position={new THREE.Vector3(position.x,position.y,position.z)} material={materials.Ch20_body} skeleton={nodes.Ch20.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('./Models/redracer.glb')



export default RedRacerModel




