/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/yellowGirl.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function YellowGirlModel({selectedImote}:any,props:any) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../Models/yellowGirl.glb')
  const { actions,names } = useAnimations(animations, group)
 
  const currentAction = useRef<any>(null);

  useEffect(() => {
   
    const findIndex: number = names.findIndex((item: any) => item === selectedImote);
    if (findIndex !== -1) {
      if (currentAction.current) {
        currentAction.current.stop(); // Stop the currently playing animation
      }
      currentAction.current = actions[names[findIndex]]; // Update the current action
      currentAction.current.reset().fadeIn(0.5).play(); // Play the new animation
    }
  }, [selectedImote]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature002" rotation={[Math.PI / 2, 0, 5.5]} position={[0,-1.3,0]} scale={0.013}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch02_Body" geometry={nodes.Ch02_Body.geometry} material={materials.Ch02_body} skeleton={nodes.Ch02_Body.skeleton} />
          <skinnedMesh name="Ch02_Cloth" geometry={nodes.Ch02_Cloth.geometry} material={materials.Ch02_body} skeleton={nodes.Ch02_Cloth.skeleton} />
          <skinnedMesh name="Ch02_Eyelashes" geometry={nodes.Ch02_Eyelashes.geometry} material={materials.Ch02_hair} skeleton={nodes.Ch02_Eyelashes.skeleton} />
          <skinnedMesh name="Ch02_Hair" geometry={nodes.Ch02_Hair.geometry} material={materials.Ch02_hair} skeleton={nodes.Ch02_Hair.skeleton} />
          <skinnedMesh name="Ch02_Sneakers" geometry={nodes.Ch02_Sneakers.geometry} material={materials.Ch02_body} skeleton={nodes.Ch02_Sneakers.skeleton} />
          <skinnedMesh name="Ch02_Socks" geometry={nodes.Ch02_Socks.geometry} material={materials.Ch02_body} skeleton={nodes.Ch02_Socks.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default YellowGirlModel
useGLTF.preload('../../../Models/yellowGirl.glb')
