name: deploy-client-srv

on:
  push:
    branches:
      - main
    paths:
      - "Metamedia_Frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: cd Metamedia_Frontend/ && docker build -t metamedia/meta-client-service .

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - run: docker push metamedia/meta-client-service

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}

      - run: doctl kubernetes cluster kubeconfig save 1cc49ce4-63a0-4db3-a5f4-e8b3e667f868

      - run: kubectl rollout restart deployment client-deployment
