name: deploy-user-srv
on:
  push:
    branches:
      - main
    paths:
      - "./User-Service/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Display directory contents
         run: ls -l User-Service/


      